insert into flight (FLIGHT_NAME, DEPARTURE_FROM, DEPARTURE_TO, PRICE) values('INDIGO','CCU','BLR',3560);
insert into flight (FLIGHT_NAME, DEPARTURE_FROM, DEPARTURE_TO, PRICE) values('VISTARA','DEL','MUM',8955);
insert into flight (FLIGHT_NAME, DEPARTURE_FROM, DEPARTURE_TO, PRICE) values('AIR INDIA','MAA','JAI',1857);
insert into flight (FLIGHT_NAME, DEPARTURE_FROM, DEPARTURE_TO, PRICE) values('KINGFISHER','IXZ','ATQ',4500);
insert into flight (FLIGHT_NAME, DEPARTURE_FROM, DEPARTURE_TO, PRICE) values('AIR ASIA','BBI','IMF',5000);
insert into flight (FLIGHT_NAME, DEPARTURE_FROM, DEPARTURE_TO, PRICE) values('ETIHAD','CHR','DXB',65000);